name = "OMNIA"
author = "Aitor"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "22b2e48b26f44857d53902e099328af79dc889493ddf75afbd031aac3107388a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
