name = "MC Comunidad Optimized"
author = "Aitor"
version = "1.3.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1d31547146a7fcf869c00c2b8bdeeef5086796def2ba6d2b84bbd353257ae583"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
