name = "MC Comunidad Optimized"
author = "Aitor"
version = "1.2.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "704598565c4c63684f7ed17898ffaf84bdccff6b54cb949055b99a41eee92e1c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
