#This file stores configuration options for Iris, such as the currently active shaderpack
#Mon Aug 03 09:33:59 PET 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=true
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=4
shaderPack=photon_v1.3b.zip
